name: blackhole
description: " An Open Source Music Player App."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.1.1
  audio_service: ^0.18.13
  audiotagger: ^2.2.1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dart_des: ^1.0.2
  device_info_plus: ^10.1.0
  file_picker: ^8.0.3
  flip_card: ^0.7.0
  flutter_archive: ^6.0.3
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.38
  marquee: ^2.2.3
  material_design_icons_flutter: ^7.0.7296
  on_audio_query: ^2.9.0
  package_info_plus: ^8.0.0
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  receive_sharing_intent: ^1.8.0
  salomon_bottom_bar: ^3.3.2
  share_plus: ^9.0.0
  sliding_up_panel: ^2.0.0+1
  supabase: ^2.2.0
  url_launcher: ^6.2.6
  url_launcher_windows: ^3.1.1
  uuid: ^4.4.0
  youtube_explode_dart: ^2.2.1
  flutter_gen: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  msix: ^3.16.7

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
msix_config:
  display_name: BlackHole
  publisher_display_name: Vinay Kumar
  identity_name: com.shadow.blackhole
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a
